name: build
on:
  pull_request:
        
jobs:
  build:
    name: the job
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [12]
           
    steps:
      - name: my first step
        env:
          MY_VAR: Hello there! My name is
          FIRST_NAME: James
          MIDDLE_NAME: T
          LAST_NAME: Kirk
        run:
          echo $MAR_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
      - name: my second step
        if: success()
        run: echo "The first step ran successfully"
      - name: my third step
        uses: actions/checkout@v1
        with:
          node-version: 12
          registery-url: https://npm.pkg.github.com/
      - name: my fourth step
        uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Message that will be displayed"
          pr-message: "message will be display on pr"
          
          
      
        
        
      
          
        

  
  
  
    
      
  
