name: test

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [12]
        os: [macos-latest, windows-latest]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: \${{ matrix.node }}
    - run: npm install
    - run: npm test
